version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"
    labels:
      - "dependencies"
      - "github-actions"

  # Maintain dependencies for Go backend
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps-backend)"
    labels:
      - "dependencies"
      - "go"

  # Maintain dependencies for npm frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps-frontend)"
    labels:
      - "dependencies"
      - "npm"