services:
  frontend:
    container_name: flow_frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - flow-network
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    container_name: flow_backend
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_PATH=/app/data/flow.db
      - OLLAMA_URL=http://ollama:11434
      - INITIAL_SYSTEM_PROMPT=You are a helpful assistant.
    volumes:
      - flow_data:/app/data
    networks:
      - flow-network
    depends_on:
      - ollama
    restart: unless-stopped
  
  ollama:
    image: ollama/ollama
    container_name: flow_ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    volumes:
      - ollama:/root/.ollama 
    networks:
      - flow-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

networks:
  flow-network:
    driver: bridge

volumes:
  flow_data: {}
  ollama:
    external: true