services:
  # Backend service
  backend:
    build:
      context: ./backend 
    container_name: flow_backend
    restart: unless-stopped
    ports:
      - "8000:8000" 
    environment:
      - REDIS_ADDR=redis:6379
    volumes:
      - uploads:/app/uploads
    networks:
      - flow-network
    depends_on:
      - redis

  # Frontend service 
  frontend:
    build:
      context: ./app
    container_name: flow_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
      - ollama
    networks:
      - flow-network

  # Redis service
  redis:
    image: redis/redis-stack:latest
    container_name: flow_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flow-network

  # Ollama service
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama 
    networks:
      - flow-network
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    restart: unless-stopped

networks:
  flow-network:

volumes:
  redis_data:
  uploads:
  ollama:
    external: true