services:
  frontend:
    container_name: flow_frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - flow-network
    depends_on:
      - backend
      - ollama
    restart: unless-stopped

  backend:
    container_name: flow_backend
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_ADDR=redis:6379
      - OLLAMA_URL=http://ollama:11434
      - INITIAL_SYSTEM_PROMPT=You are a helpful assistant.
      - INITIAL_MAIN_MODEL=qwen3:0.6b
      - INITIAL_SUPPORT_MODEL=qwen3:0.6b
    volumes:
      - uploads:/app/uploads
    networks:
      - flow-network
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    container_name: flow_redis
    networks:
      - flow-network
    volumes:
      - redis_data:/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: flow_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama 
    networks:
      - flow-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

networks:
  flow-network:
    driver: bridge

volumes:
  redis_data:
  uploads:
  ollama:
    external: true