services:
  # Бекенд сервіс (Node.js + Express + SQLite)
  backend:
    build:
      context: ./backend
    container_name: flow_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
    volumes:
      - sqlite_data:/usr/src/app/data
    networks:
      - flow-network

  # Фронтенд сервіс (Nginx роздає зібраний React/Vite)
  frontend:
    build:
      context: ./app
    container_name: flow_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
      - ollama
    networks:
      - flow-network

  # Ollama сервіс
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama 
    networks:
      - flow-network
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    restart: unless-stopped
      

networks:
  flow-network:


# Визначаємо іменовані томи, якими керує Docker Compose
volumes:
  sqlite_data:
  ollama:
    external: true