services:
  flow-ai:
    build:
      context: ..
      dockerfile: Dockerfile
      target: final
    ports:
      - "${APP_PORT:-3000}:80"
    restart: unless-stopped
    networks:
      - flow-ai-net

  ollama:
    restart: unless-stopped
    networks:
      - flow-ai-net
