services:
  flow-ai:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3000}:80"
    restart: unless-stopped

  ollama:
    restart: unless-stopped

volumes:
  ollama-data:
    name: ollama
    external: true
