services:
  flow-ai:
    env_file:
      - ../.env
    environment:
      - OLLAMA_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - DATABASE_PATH=${DATABASE_PATH:-/data/flow.db}
      - INITIAL_SYSTEM_PROMPT=You are a helpful assistant. Always respond in Markdown format.
      - LOG_LEVEL=INFO
    volumes:
      - flow-ai-data:/data
    networks:
      - flow-ai-net
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - flow-ai-net
    tty: true

networks:
  flow-ai-net:
    driver: bridge

volumes:
  flow-ai-data:
  