services:
  flow-ai:
    container_name: flow-ai-backend-dev
    build:
      context: ..
      dockerfile: Dockerfile
      target: builder-backend
    working_dir: /src
    command: go run ./cmd/server
    volumes:
      - ../backend:/src
    ports:
      - "8000:8000"
    environment:
      LOG_LEVEL: "DEBUG"
      DATABASE_PATH: "/src/flow-dev.db"
    networks:
      - flow-ai-net

  frontend:
    container_name: flow-ai-frontend-dev
    build:
      context: ..
      dockerfile: Dockerfile
      target: builder-frontend
    command: npm run dev -- --host
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    networks:
      - flow-ai-net

  ollama:
    container_name: flow-ai-ollama-dev
    ports:
      - "11434:11434"
    networks:
      - flow-ai-net

volumes:
  frontend_node_modules: {}
